SongSuggestionDatabase/Models/Request.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SongSuggestionDatabase.Models
{
    [Table("Songs")]
    public class Request
    {
        [Key]
        public Guid Id { get; set; }

        [Display(Name = "Time Requested")]
        public DateTime TimeRequested { get; set; }

        [Display(Name = "Time Completed")]
        public DateTime? TimeCompleted { get; set; }

        [Display(Name = "Requested By")]
        [MaxLength(30)]
        public string RequestedBy { get; set; }

        [ForeignKey(nameof(Currency))]
        [MaxLength(5)]
        public string CurrencyCode { get; set; }

        [Display(Name = "Currency")]
        public Currency Currency { get; set; }

        [Display(Name = "Amount")]
        [Column(TypeName = "decimal(8, 2)")]
        public decimal? Amount { get; set; }

        [Display(Name = "to USD")]
        [Column(TypeName = "decimal(8, 2)")]
        public decimal? USDAmount { get; set; }

        [Display(Name = "Title")]
        [MaxLength(50)]
        public string Title { get; set; }

        [Display(Name = "Artist")]
        [MaxLength(50)]
        public string Artist { get; set; }

        [ForeignKey(nameof(Episode))]
        public Guid? EpisodeId { get; set; }
        
        [Display(Name = "Episode")]
        public Episode? Episode { get; set; }

        [Display(Name = "Playing?")]
        public bool IsPlaying { get; set; }

        [ForeignKey(nameof(Rating))]
        public Guid? RatingId { get; set; }

        [Display(Name = "Rating")]
        public Rating? Rating { get; set; }

        [Display(Name = "Detailed Rating")]
        [MaxLength(200)]
        public string? DetailedRating { get; set; }

        [Display(Name = "Quote")]
        [MaxLength(200)]
        public string? Quote { get; set; }

        [Display(Name = "Status")]
        [MaxLength(15)]
        public string Status { get; set; }

        public bool IsInQueue => !IsPlaying && TimeCompleted == null;

        public bool IsComplete => !IsPlaying && TimeCompleted != null;
    }
}

SongSuggestionDatabase/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json.Linq;
using SongSuggestionDatabase.Data;
using SongSuggestionDatabase.Models;
using SongSuggestionDatabase.Models.Output;

namespace SongSuggestionDatabase.Controllers
{
    [Authorize(Roles = "Moderator")]
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _config;
        private HttpClient _client = new HttpClient();

        public RequestsController(ApplicationDbContext context, IConfiguration config)
        {
            _context = context;
            _config = config;
        }

        // GET: Requests
        [AllowAnonymous]
        public async Task<IActionResult> Index(string? search, string sortBy = "date", string order = "desc")
        {
            ViewBag.SearchString = search;

            var sortOptions = _context.CatalogSortOptions.OrderBy(s => s.Id);
            ViewBag.CatalogSortOptions = new SelectList(sortOptions, "Value", "Name");

            bool orderIsAscending = order == "asc";

            IQueryable<Request> requests = _context.Requests
                .Include(r => r.Currency)
                .Include(r => r.Episode);

            if (!search.IsNullOrEmpty())
                requests = requests.Where(r => r.Title.Contains(search!) ||
                                               r.Artist.Contains(search!));
            
            switch (sortBy)
            {
                case "artist":
                    requests = orderIsAscending ?
                        requests.OrderBy(r => r.Artist)
                            .ThenBy(r => r.Title)
                            .ThenBy(r => r.Episode!.Date) :
                        requests.OrderByDescending(r => r.Artist)
                            .ThenBy(r => r.Title)
                            .ThenBy(r => r.Episode!.Date);

                    break;

                case "title":
                    requests = orderIsAscending ?
                        requests.OrderBy(r => r.Title)
                            .ThenBy(r => r.Artist)
                            .ThenBy(r => r.Episode!.Date) :
                        requests.OrderByDescending(r => r.Title)
                            .ThenBy(r => r.Artist)
                            .ThenBy(r => r.Episode!.Date);

                    break;

                default:
                    requests = orderIsAscending ?
                        requests.OrderBy(r => r.Episode!.Date)
                            .ThenBy(r => r.Artist) :
                        requests.OrderByDescending(r => r.Episode!.Date)
                            .ThenBy(r => r.Artist);

                    break;
            }

            ViewBag.RatingCounts = await GetRatingCounts(requests);

            return View(await requests.ToListAsync());
        }

        // GET: Requests/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Requests == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // GET: Requests/Create
        public IActionResult Create()
        {
            var currencies = _context.Currencies.OrderBy(c => c.Code);
            ViewBag.Currencies = new SelectList(currencies, "Code", "Symbol");
            
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RequestedBy,CurrencyCode,Amount,Title,Artist,EpisodeId")] Request request)
        {
            if (ModelState.IsValid)
            {
                request.Id = Guid.NewGuid();
                request.TimeRequested = DateTime.Now;
                request.Status = "In Queue";
                request.Episode = _context.Episodes.FirstOrDefault(e => e.Id == request.EpisodeId);
                request.USDAmount = request.Currency!.Code == "USD" ?
                    request.Amount :
                    await ConvertToUSDAsync(request.Currency!, (decimal)request.Amount!);

                // Request amounts cannot be less than $10 USD
                if (request.USDAmount < 10)
                {
                    ViewBag.Message = new DangerMessage("Request amount cannot be less than $10 USD.");
                    return View();
                }

                // Banned artists cannot be played if banned list checks are enabled
                bool bannedListChecksEnabled = request.Episode!.BannedListChecksEnabled == "Yes";
                bool artistIsBanned = await CheckBannedListAsync(request.Artist);
                if (bannedListChecksEnabled && artistIsBanned)
                {
                    ViewBag.Message = new DangerMessage($"{request.Artist} is banned.");
                    return View();
                }

                // Songs that have already been done cannot be played if catalog checks are enabled
                bool catalogChecksEnabled = request.Episode!.CatalogChecksEnabled == "Yes";
                bool songExists = await CheckCatalogAsync(request.Title, request.Artist);
                if (catalogChecksEnabled && songExists)
                {
                    ViewBag.Message = new DangerMessage($"{request.Title} by {request.Artist} has already been done.");
                    return View();
                }

                // If we have reached this point, this request has passed the validation checks!
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var currencies = _context.Currencies.OrderBy(c => c.Code);
            ViewBag.Currencies = new SelectList(currencies, "Code", "Symbol");

            return View(request);
        }

        // GET: Requests/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Requests == null)
            {
                return NotFound();
            }

            var request = await _context.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Amount,USDAmount,Title,Artist,RatingId,DetailedRating,Quote")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(request);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        // GET: Requests/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Requests == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Requests == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Request'  is null.");
            }
            var request = await _context.Requests.FindAsync(id);
            if (request != null)
            {
                _context.Requests.Remove(request);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestExists(Guid id)
        {
            return (_context.Requests?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private void ResetDefaultRequestHeaders(HttpClient client)
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        ///     Check the catalog to see if a song has been done before.
        /// </summary>
        /// <param name="title">The title of the song.</param>
        /// <param name="artist">The artist of the song.</param>

SongSuggestionDatabase/Views/Requests/Create.cshtml
@model Request

@{
    ViewData["Title"] = "Create";
}

<h1>New Request</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Requests" asp-action="Create">
            <input type="hidden" asp-for="EpisodeId" />
            <div class="container">
                <div class="row">
                    <div class="col" id="superchat-area">
                        <p>
                            Paste superchat here:
                        </p>
                        <textarea id="superchat-paste-area"></textarea>
                    </div>
                    <div class="col" id="request-info">
                        <div class="form-group" id="requester-area">
                            <label asp-for="RequestedBy" class="control-label"></label>
                            <input asp-for="RequestedBy" class="form-control" id="requester-field" />
                        </div>
                        <div class="form-group" id="amount-area">
                            <select id="currency-dropdown" asp-for="CurrencyCode" asp-items="@ViewBag.Currencies"></select>
                            <input type="text" class="form-control" asp-for="Amount" id="amount-field" />
                        </div>
                        <div class="form-group" id="title-area">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" id="title-field" />
                        </div>
                        <div class="form-group" id="switch-title-and-artist-area">
                            <button class="btn btn-secondary" onclick="SwitchTitleAndArtist">Switch Title and Artist</button>
                        </div>
                        <div class="form-group" id="artist-area">
                            <label asp-for="Artist" class="control-label"></label>
                            <input asp-for="Artist" class="form-control" id="artist-field" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SongSuggestionDatabase/Views/Requests/Delete.cshtml
@model SongSuggestionDatabase.Models.Request

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeRequested)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeRequested)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.USDAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.USDAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetailedRating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetailedRating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quote)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SongSuggestionDatabase/Views/Requests/Details.cshtml
@model SongSuggestionDatabase.Models.Request

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Request</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeRequested)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeRequested)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.USDAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.USDAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetailedRating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetailedRating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quote)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SongSuggestionDatabase/Views/Requests/Edit.cshtml
@model Request

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TimeRequested" class="control-label"></label>
                <input asp-for="TimeRequested" class="form-control" />
                <span asp-validation-for="TimeRequested" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="USDAmount" class="control-label"></label>
                <input asp-for="USDAmount" class="form-control" />
                <span asp-validation-for="USDAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DetailedRating" class="control-label"></label>
                <input asp-for="DetailedRating" class="form-control" />
                <span asp-validation-for="DetailedRating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quote" class="control-label"></label>
                <input asp-for="Quote" class="form-control" />
                <span asp-validation-for="Quote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SongSuggestionDatabase/Views/Requests/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using SongSuggestionDatabase.Models.Users
@model IEnumerable<SongSuggestionDatabase.Models.Request>

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Full Catalog";
    bool userIsAdminOrModerator = User.IsInRole("Admin") || User.IsInRole("Moderator");

    string GetRatingColor(char? rating)
    {
        string ratingColor = "bg-";

        switch (rating)
        {
            case '+':
                ratingColor = "success";
                break;

            case '=':
                ratingColor = "warning";
                break;

            case '-':
                ratingColor = "danger";
                break;

            default:
                return "";
        }

        return ratingColor + "-subtle";
    }
}

<h1>@ViewBag.Title</h1>

<form asp-action="Index" method="get">
    Search: <input type="text" name="search" value="@ViewBag.SearchString" />
    Sort by: @Html.DropDownList("sortOrder", (IEnumerable<SelectListItem>)ViewBag.CatalogSortOptions, new { onchange="submit()" })
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Song
            </th>
            <th>
                Date
            </th>
            <th>
                Rating
            </th>
            @if (userIsAdminOrModerator)
            {
                <th>
                    Actions
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var song in Model) {
            <tr>
                <td>
                    <span class="title">@song.Title</span><br />
                    <span class="artist">@song.Artist</span>
                </td>
                <td>
                    @song.Episode!.Date.ToShortDateString()
                </td>
                <td class="@GetRatingColor(song.Rating!.Symbol)">
                    @if (song.Rating!.IconPath != null)
                    {
                        <img src="@song.Rating.IconPath" />
                    }
                    else
                    {
                        @song.Rating.Symbol
                    }
                </td>
                @if (userIsAdminOrModerator)
                {
                    if (song.IsInQueue)
                    {
                        <partial name="Partials/SongInQueue.cshtml" />
                    }
                    else if (song.IsComplete)
                    {
                        <partial name="Partials/SongReviewed.cshtml" />
                    }
                    else
                    {
                        <partial name="Partials/SongIsPlaying.cshtml" />
                    }
                }
            </tr>
        }
    </tbody>
</table>