SongSuggestionDatabase/Controllers/CurrenciesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json.Linq;
using SongSuggestionDatabase.Data;
using SongSuggestionDatabase.Models;
using System.Net.Http.Headers;

namespace SongSuggestionDatabase.Controllers
{
    public class CurrenciesController : Controller
    {
        private readonly ILogger<CurrenciesController> _logger;
        private readonly IConfiguration _config;
        private readonly ApplicationDbContext _context;
        private readonly string AppJson;

        public CurrenciesController(ILogger<CurrenciesController> logger,
                                    IConfiguration config,
                                    ApplicationDbContext context)
        {
            _logger = logger;
            _config = config;
            _context = context;

            AppJson = _config.GetValue<string>("RequestHeaders:AppJson")!;
        }
        
        public async Task<IActionResult> Index(string? search)
        {
            ViewBag.CurrencySearch = search;

            Dictionary<string, decimal> conversionRates = await GetConversionRates();
            IQueryable<Currency> currencies = _context.Currencies.OrderBy(c => c.Code);

            if (!search.IsNullOrEmpty())
            {
                currencies = currencies.Where(c => c.Symbol.Contains(search!) ||
                                                   c.Code.Contains(search!) ||
                                                   c.Name.Contains(search!));

                conversionRates = FilterCurrencyDictionary(conversionRates, currencies.ToList());
            }

            ViewBag.Currencies = currencies;
            
            return View(conversionRates);
        }

        private string GetCurrencyConverterAPIKey()
        {
            return _config.GetValue<string>("Secrets:CurrencyConverter:APIKey")!;
        }

        private async Task<Dictionary<string, decimal>> GetConversionRates()
        {
            Dictionary<string, decimal>? conversionRates = null;
            
            string key = GetCurrencyConverterAPIKey();
            string endpoint = $"https://v6.exchangerate-api.com/v6/{key}/latest/USD";

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(AppJson));
                var response = await client.GetAsync(endpoint);

                if (response.IsSuccessStatusCode)
                {
                    var result = await ParseJSON(response);
                    conversionRates = result["conversion_rates"]!.ToObject<Dictionary<string, decimal>>()!;

                    conversionRates.Remove("USD");
                }
            }

            return conversionRates!;
        }

        private async Task<JObject> ParseJSON(HttpResponseMessage response)
        {
            string json = await response.Content.ReadAsStringAsync();
            JObject result = JObject.Parse(json);

            return result;
        }

        /// <summary>
        ///     Filter out a list of currencies from the currency dictionary.
        /// </summary>
        /// <param name="fullDictionary">The full dictionary of currencies.</param>
        /// <param name="filteringList">The list of currencies to filter out.</param>
        /// <returns>The new dictionary of currencies.</returns>
        private Dictionary<string, decimal> FilterCurrencyDictionary(Dictionary<string, decimal> fullDictionary,
                                                                     List<Currency> filteringList)
        {
            // Store the new dictionary here
            Dictionary<string, decimal> filteredCurrencies = new();
            
            // For each currency to be filtered...
            foreach (var currency in filteringList)
            {
                // If the currency's code is a key in the dictionary, add it and its conversion rate to the new dictionary
                if (fullDictionary.TryGetValue(currency.Code, out decimal rate))
                    filteredCurrencies.Add(currency.Code, rate);
            }

            // Return the filtered currency dictionary
            return filteredCurrencies;
        }
    }
}

SongSuggestionDatabase/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SongSuggestionDatabase.Models;
using System.Diagnostics;

namespace SongSuggestionDatabase.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Rules()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SongSuggestionDatabase/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Song Suggestion Database</h1>
    <p>Welcome to the new home of the Song Suggestion catalog!</p>
</div>

SongSuggestionDatabase/Views/Home/Rules.cshtml
@{
    ViewData["Title"] = "Rules";
}

<h1>Rules</h1>

<ul>
    <li>
        Send your request via YouTube superchat. Minimum $10 USD. Higher amount = higher on the playlist.
    </li>
    <li>
        Any currency is accepted, as long as the amount in that currency meets the $10 USD minimum. If in doubt, feel free to use our <a asp-controller="Currencies" asp-action="Index">real-time currency converter</a> for accurate conversions.
    </li>
    <li>
        Alternatively, you can request a song via <a href="https://streamlabs.com/becometheknight/tip" target="_blank">StreamLabs</a> if you don't want to use YouTube superchat.
    </li>
    <li>
        Make sure to check the <a href="#">catalog</a> and <a href="#">banned list</a> to make sure that the song you are requesting has not been done before, and that the artist you are requesting has not been banned from the livestreams.
    </li>
    <li>
        I reserve the right to invoke the "F you" privilege and immediately skip your song if I absolutely can't stand it. I typically give every song a chance, but mind your audience.
    </li>
</ul>